controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_left_joint1
      - panda_left_joint2
      - panda_left_joint3
      - panda_left_joint4
      - panda_left_joint5
      - panda_left_joint6
      - panda_left_joint7
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_left_finger_joint1
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_right_joint1
      - panda_right_joint2
      - panda_right_joint3
      - panda_right_joint4
      - panda_right_joint5
      - panda_right_joint6
      - panda_right_joint7
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_right_finger_joint1
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: default_left_pose