left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_left_joint1
    - panda_left_joint2
    - panda_left_joint3
    - panda_left_joint4
    - panda_left_joint5
    - panda_left_joint6
    - panda_left_joint7
  gains:
    panda_left_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_left_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_right_joint1
    - panda_right_joint2
    - panda_right_joint3
    - panda_right_joint4
    - panda_right_joint5
    - panda_right_joint6
    - panda_right_joint7
  gains:
    panda_right_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_right_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_left_finger_joint1
  gains:
    panda_left_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_right_finger_joint1
  gains:
    panda_right_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1