left_arm_group: "left_arm"
right_arm_group: "right_arm"
left_hand_group: "left_hand"
right_hand_group: "right_hand"
dual_arm_group: "dual_arm"
dual_hand_group: [ "dual_hand_left", "dual_hand_right" ]

default_dual_arm_joint_state: [ 0.0, -2.8, 0.42, 2.67, -2.46, 0.14, 2.99, 0.07,-0.19, -0.06, 0.42, -1.81, -0.04, 2.01, 0.24 ]